# Read libraries:
library(ggplot2)
library(dplyr)  
library(sf)
library(tibble)
library(readr)
library(purrr)
library(gridExtra)
library(viridis)
library(tinyVAST)
library(DescTools)
library(boot)
library(stars)
library(lubridate)
library(blockCV)
library(fmesher)
library(corrplot)
library(car)
library(future)
library(tidyr)
library(ggdendro)
library(scales)
library(fpc)
library(factoextra)
library(rphylopic)
source('code/2_multi/parameters_for_plots.R')
source('code/aux_functions.R')

# Define plot and data folder:
# Data folder:
data_folder = file.path("data", "2_multi", this_type)
dir.create(data_folder, showWarnings = FALSE, recursive = TRUE)
# Plot folder:
plot_folder = file.path("figures", "2_multi", this_type)
dir.create(plot_folder, showWarnings = FALSE, recursive = TRUE)
# Model folder:
model_folder = file.path("model", "2_multi", this_type)
dir.create(model_folder, showWarnings = FALSE, recursive = TRUE)
